apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.accountservice.replicas }}
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: {{ .Values.accountservice.image }}
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
          livenessProbe:
            exec:
              command: ["sh", "-c", "kill -0 1"]
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
