apiVersion: apps/v1
kind: Deployment
metadata:
  name: iws-chainclient
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.chainclient.replicas }}
  selector:
    matchLabels:
      app: iws-chainclient
  template:
    metadata:
      labels:
        app: iws-chainclient
    spec:
      containers:
        - name: iws-chainclient
          image: {{ .Values.chainclient.image }}
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKER
              value: "kafka:9092"
            - name: ETHEREUM_RPC
              value: "http://anvil:8545"
            - name: CONTRACT_ADDRESS
              value: {{ .Values.anvil.contractAddress | quote }}
            - name: OPERATOR_PRIV_KEY
              value: {{ .Values.anvil.operatorPrivKey | quote }}
          livenessProbe:
            exec:
              command: ["sh", "-c", "kill -0 1"]
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
