/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWSSettlement__factory } from "./IWSSettlement__factory";
export { MockERC20__factory } from "./MockERC20__factory";
